doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geometry:     CrEOF\Spatial\DBAL\Types\GeometryType
            point:        CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:      CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            multipolygon: CrEOF\Spatial\DBAL\Types\Geometry\MultiPolygonType
            linestring:   CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
          numeric_functions:
            POINT: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
            ST_CONTAINS: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
            DEGREES: DoctrineExtensions\Query\Mysql\Degrees
            ACOS: DoctrineExtensions\Query\Mysql\Acos
            COS: DoctrineExtensions\Query\Mysql\Cos
            RADIANS: DoctrineExtensions\Query\Mysql\Radians
            SIN: DoctrineExtensions\Query\Mysql\Sin
          string_functions:
            LEAST: DoctrineExtensions\Query\Mysql\Least

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
